### ISSUE TITLE
Create GPG key for signing jamulus deb repository

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/repos#1]
To kick off this repository, we need to create a GPG key for signing deb packages. Should we share it or can I create and then delete it locally on my machine?

@jamulussoftware/maindevelopers

**Comment by pljones** [comment]
I think we want something where the key must be signed by each of the main developers to be valid and be revocable by any of the main developers.  I'm not clear from reading up on things how the main key would "normally" be created.  Presumably we'd sign it over a private channel on somewhere like Discord.  And I've also no clear idea on how it would be made revocable.

**Comment by ann0see** [comment]
Hmm. Maybe a CA is involved then. But no idea.

**Comment by gilgongo** [comment]
@pljones this seems to be being discussed in two places https://github.com/jamulussoftware/jamulus/issues/1495#issuecomment-1455130919 - but is this the way to do it? https://mikeross.xyz/create-gpg-key-pair-with-subkeys/ ?

Not sure I fully understand, but it seems to imply that along with things like revocation, we'd also not need to pass the main key's private key around (just one of us store it offline somewhere).

**Comment by ann0see** [comment]
These issues are related. True. This one is about the deb repository while the other one is more general (also about E-Mails).

**Comment by gilgongo** [comment]
In each case (even if we have separate deb and "admin" keys) we'd want some way of having a Jamulus key pair that meant we could sign (and maybe revoke?) the primary key without having to deal with the secret key for it. The link above seems to be explaining how to do that, but I'm not sure.

**Comment by ann0see** [comment]
I think the sub key approach is probably not the best approach if it means that all keys need to be created on one machine. 

I think a certificate authority would be a more standard approach. I think this also allows revocation etc.

**Comment by ann0see** [comment]
Fixed by Volker in the mentioned issue (1495)
